### ISSUE TITLE
[test:vitest-run] TypeError: unmount is not a function

### ISSUE THREAD

**Issue by quantuminformation** [solidjs/solid-testing-library#38] opened 2023-05-18 11:41 UTC
All of a sudden, I started to get

<img width="910" alt="image" src="https://github.com/solidjs/solid-testing-library/assets/216566/77c2d150-9bbd-46a8-b046-034800b5e751">

for tests like

<img width="1123" alt="image" src="https://github.com/solidjs/solid-testing-library/assets/216566/043f978a-b590-430f-9450-fbb4781bc85b">

**Comment by atk** [comment] 2023-05-18 13:25
You usually don't have to unmount manually. Still, this is an error that I need to investigate, so thanks for bringing this to my attention. I will have a look later.

**Comment by quantuminformation** [comment] 2023-05-18 13:28
gladly removing onmount_)

**Comment by atk** [comment] 2023-05-18 16:14
Can you show me your vite(st).config?

**Comment by quantuminformation** [comment] 2023-05-18 19:12
minus our proxy
```
/// <reference types="vitest" />
/// <reference types="vite/client" />

import { defineConfig } from 'vite';
import solid from 'vite-plugin-solid';
import packageJson from './package.json';

export default defineConfig({
  test: {
    environment: 'jsdom',
    transformMode: {
      web: [/.[jt]sx?/],
    },
    deps: {
      registerNodeLoader: true,
    },
    threads: false,
    isolate: false,
  },
  plugins: [solid()],
  resolve: {
    conditions: ['development', 'browser'],
  },
  build: {
    target: 'esnext',
    sourcemap: true,
  },
  define: {
    __VERSION_NUMBER__: `"${packageJson.version}"`,
  },

,
});
```

**Comment by atk** [comment] 2023-05-18 20:04
Thanks, I'll try to reproduce.

**Comment by amireldor** [comment] 2023-05-20 10:08
Not sure if related, but I'm getting a `TypeError: dispose is not a function`. I've just added vitest and solid-testing-library to my project.

```tsx
it("should do something", () => {
  render(() => <div>amir</div>);
  expect(screen.queryByText("amir")).toBeDefined();
});
```

![image](https://github.com/solidjs/solid-testing-library/assets/1746811/e5727551-949e-4ca6-96b0-ba7d761d2614)

Following thread.

**Comment by atk** [comment] 2023-05-21 20:45
Unfortunately, I was not able to reproduce the issue. All I can do is to offer you a pair debugging session if you can make some time. You can find me on the Solid Discord to schedule a session; feel free to ping me.

**Comment by amireldor** [comment] 2023-05-21 20:51
@atk Hi there, I'll ping you in the next few days. Hopefully we'll be able to schedule and tackle this. Thanks.

**Comment by ThaisRobba** [comment] 2023-05-21 23:02
Hey folks, I think I know the issue. What node version are you using? Try are running node@16


I was getting `dispose is not a function`. I noticed I could not get any solidjs + vitest tests to run locally but on StackBlitz they worked.

After reviewing every dependency version, the last thing was checking the node version. I was running node v20, changed to v16, voilá, the tests work.

**Comment by atk** [comment] 2023-05-22 03:57
Thanks, I'll go check with node@20.

**Comment by MarkLeMerise** [comment] 2023-05-23 17:11
@ThaisRobba is definitely onto something. I've been running into the `dispose is not a function` error with Node 20, but just ran with Node 16 & 18 fine. Thanks for looking into this @atk!

**Comment by atk** [comment] 2023-05-23 19:05
There's a workaround: you can inline /solid-js/, that fixes the issue. Anyways, the problem is with the vitest loader that has export conditions broken by node-20, so I'm going to close this issue, as it is unrelated to solid-testing-library. I have already notified them on discord, so I'm sure there will be a solution soon.

**Closed by atk** 2023-05-23 19:05 UTC

**Comment by quantuminformation** [comment] 2023-05-26 14:22
how do we
` you can inline /solid-js/,`

**Comment by atk** [comment] 2023-05-26 15:50
Sorry to be so ambiguous; this goes in the vite(st) config:

```ts
{
  test: {
    environment: 'jsdom',
    transformMode: {
      web: [/\.[jt]sx?$/],
    },
    // solid needs to be inline to work around
    // a resolution issue in vitest with node-20:
    deps: {
      inline: [/solid-js/],
    },
  },
  // Your other config here
}
```

**Comment by quantuminformation** [comment] 2023-05-30 09:58
I was also getting this issue in node 16

anyway your fix works on v16, thx

<img width="1547" alt="image" src="https://github.com/solidjs/solid-testing-library/assets/216566/4916c0b7-5547-4fce-b32b-6c3e3d74d1b0">
